language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21

sudo: false

cache:
  directories:
    - $HOME/.gradle
